### ISSUE TITLE
Right/Left Click issue

### ISSUE THREAD

**Issue by jquimera** [slavanga/pusha#2]
Within the off-canvas there is a list of links. I wanted the offcanvas to automatically close when clicked on a link with the left click, but only with the left click. The panel can remain open when right-clicked. In case to open a link in a new tab.

https://codepen.io/johnquimera/pen/zjYJpq

**Comment by slavanga** [comment]
You can use the API to close the panel when a link in the navigation is clicked.

```js
[].forEach.call(document.querySelectorAll('.primary-nav a'), function(el) {
    el.addEventListener('click', menuLeft.close);
});
```

Note: External links without ```target="blank"```don't work in CodePen.

**Comment by jquimera** [comment]
@slavanga works fine, thanks.

**Comment by jquimera** [comment]
@slavanga Why in localhost, the links do not open, even with target = "blank"? The offcanvas closes as expected, but the link does not open.

**Comment by slavanga** [comment]
Please try updating pusha.js as I have pushed an update this morning.

**Comment by jquimera** [comment]
@slavanga Amazing. Its working. Thx.
